### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by Ekultek** [AutoSploit/AutoSploit#3]
What the fuck is this? Can you at least make it less obvious you’re ripping off one of my projects?

**Comment by NullArray** [comment]
*Our

Lol, also, when did i release V1? I forgot.

**Comment by Ekultek** [comment]
@NullArray I was gonna say our, but I couldnt tag you until you commented. Idk sometime in February right?

**Comment by NullArray** [comment]
Right, so earliest dates on this repo say somewhere in 2017. I think RootUp just came up with the same idea, but we fleshed it out and he left it to become abandonware.

**Comment by Ekultek** [comment]
Idgaf I feel like starting a war today.

**Comment by NullArray** [comment]
Lmao knock yourself out.

**Comment by Ekultek** [comment]
I don’t think he’ll comment on this.

**Comment by fredhagedorn** [comment]
I just fucking lost my sides reading this Issue. @Ekultek, man, you are just cool as fuck. No homo.

**Comment by Ekultek** [comment]
@fredhagedorn I’m so much cooler online.

**Comment by fredhagedorn** [comment]
@Ekultek Makes sense; btw that's why I like and use - and use in a very fucking nice way - everything you code for the community.

**Comment by RootUp** [comment]
Hey guys, 

Hold on, was off for few days, I saw this thread now.

As far I can see 
`https://api.github.com/repos/NullArray/AutoSploit` created_at	"2018-01-30T17:47:18Z"
and mine was on,
`https://api.github.com/repos/Rootup/AutoSploit` created_at	"2017-06-18T16:31:15Z"

To be honest, i am not ripping any of your projects nor any idea was taken from your repo.
However, I tweeted my Autosploit repo on 20 Jun 2017,
`https://twitter.com/mishradhiraj_/status/877379775945334784`
Where if, I see your @NullArray 9:33 AM - 30 Jan 2018
`https://twitter.com/Real__Vector/status/958392622900502529`

Please correct me if i am wrong.

**Comment by Ekultek** [comment]
You’re not wrong I was just being an asshole that day, sorry man, I really like your project
